### ISSUE TITLE
NVJPEG_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by pytho12** [NVIDIA/CUDALibrarySamples#153] opened 2023-10-25 12:15 UTC
Hello, I am using a T4 card. When using status = nvjpegCreateEx(NVJPEG_BACKEND_HARDWARE, &dev_allocator, NULL, 0, &nv_handle ); error: NVJPEG_STATUS_ARCH_MISMATCH

**Comment by zohebk-nv** [comment] 2023-11-01 22:36
Hello, this is expected behavior since T4 does not support HW accelerated decode. You may want to fallback to `NVJPEG_BACKEND_DEFAULT ` . You can refer to this code [snippet](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp#L331-#L338).

**Comment by pytho12** [comment] 2023-11-02 06:39
In the nvJPEG case, why is there no encoding case?

**Comment by pytho12** [comment] 2023-11-02 08:51
In the nvJPEG case, why is there no encoding case?  I would be grateful if you could provide encoding cases and test performance cases for nvJPEG.

**Comment by zohebk-nv** [comment] 2023-11-02 19:58
Will look into adding a new nvjpeg sample which focuses on encode. 
For nvjpeg encode, you can take a look at the [Image-Resize sample] (https://github.com/NVIDIA/CUDALibrarySamples/tree/master/nvJPEG/Image-Resize). This sample uses the [nvjpeg encode APIs](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvJPEG/Image-Resize/imageResize.cpp#L241-#L267).

**Comment by zohebk-nv** [comment] 2023-11-02 22:25
you can also refer to the nvjpeg encoder sample here - https://github.com/NVIDIA/cuda-samples/tree/master/Samples/4_CUDA_Libraries/nvJPEG_encoder

**Comment by zohebk-nv** [comment] 2023-12-04 21:59
marking as close. Feel free to reopen if you need additional information. Will add the encoder sample as part of this issue - https://github.com/NVIDIA/CUDALibrarySamples/issues/161

**Closed by zohebk-nv** 2023-12-04 21:59 UTC
Labels: nvJPEG
