### ISSUE TITLE
nvjpeg2000 (Reversible(5-3) wavelet transforms) is not always 100% lossless

### ISSUE THREAD

**Issue by dweckmann** [NVIDIA/CUDALibrarySamples#110] opened 2023-02-15 09:53 UTC
Hi,

When encoding some test image (attached as "source.png"), using nvjepg2000 with "Reversible(5-3) wavelet transforms" which is advertised as lossless, the result is not the exact copy of the source. Some pixels value differ: for example at index 255, the source pixel is r=255, g=0, b=0 and the encoded read back result is r=254, g=0, b=0.

There is no such problem when using openJPEG, or even JASPER to write and read back the image.

Source image: 
![source](https://user-images.githubusercontent.com/24878642/218981208-d56bec43-9c33-473b-9f01-ebc0b66133b2.png)

Encoded image (as zip because I cannot upload .jp2):
[result.jp2.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/10741213/result.jp2.zip)

**Comment by maheshkha** [comment] 2023-02-16 07:44
Hi @dweckmann ,
Thank you for reporting this issue.
We unable to reproduce this issue, if you share reproducible or more details to look into this.

**Comment by dweckmann** [comment] 2023-02-16 08:32
> Hi @dweckmann , Thank you for reporting this issue. We unable to reproduce this issue, if you share reproducible or more details to look into this.

Hi,

Sorry, I forgot to say that I use a block size of 32 (nvjpeg2kEncodeConfig_t.code_block_w and code_block_h = 32), because it is faster.

But I have another test case which also fail with code_block_w = 64 (using uniform random data).

Thank you for your help !

**Comment by mkhadatare** [comment] 2023-02-22 06:23
Hi @dweckmann 
We are unable to repro the issue with cblk size = 32.

The reconstructed RGB value for me at y = 0, and x = 255 is 255,0,0.

If you share self-contained reproducible will be helpful. 
Or 
Can you provide additional details about encoder config settings?
What values do you set in this nvjpeg2kEncodeParamsSetQuality API?
What GPUs and OS you have seen this issue?

**Comment by trybicki-nv** [comment] 2023-08-14 13:25
Closing (unable to reproduce). Feel free to reopen if you have any more comments/data to reproduce.

**Closed by trybicki-nv** 2023-08-14 13:25 UTC
Labels: nvJPEG2000
